project:
  type: book
  output-dir: _book

book:
  title: "Soil Dynamics and Earthquake Engineering"
  author: "Vikas Sharma"
  date: "2/06/2025"
  reader-mode: true
  search: true
  repo-url: https://github.com/poromechanics/sdee/
  site-url: https://poromechanics.github.io/sdee
  repo-actions: [edit, issue]
  downloads: [pdf,epub]
  sharing: [twitter, linkedin]
  favicon: ./figures/favicon.png
  cover-image: ./figures/cover.svg
  cover-image-alt: SDEE
  twitter-card: true
  page-navigation: true
  page-footer:
    left: "Copyright 2025, Vikas Sharma" 
    right: 
      - icon: github
        href: https://github.com/vickysharma0812
      - icon: twitter
        href: https://twitter.com/vickysharma0812
      - icon: linkedin
        href: https://linkedin.com/in/vickysharma0812
  sidebar:
      style: docked
      background: light
  chapters:
    - index.md
    - intro.md
    - tdg-first-order-ode.md
    - tdg-second-order-ode.md
    - elastic-waves-introduction.md
    - elastic-waves-body-waves-in-solids.md
    - elastic-waves-surface-waves-in-solids.md
    - elastic-waves-radiation-boundary.md
    - elastodynamics-introduction.md
    - elastodynamics-vstfem.md
    - dynamic-ssi-vstfem.md
    - dynamic-ssi-drs-introduction.md
    - dynamic-ssi-drs-equations.md
    - dynamic-ssi-drs-vstfem.md
    - dynamic-ssi-drs-nonlinear-problem.md
    - dynamic-ssi-drs-nonlinear-vstfem.md
    - summary.md
    - references.md
  # appendices:
# crossref:
#   eq-labels: roman

bibliography: references.bib

comments:
  hypothesis: true

execute:
  freeze: auto

format:
  html:
    theme:
      - cosmo
      - brand
  # pdf:
  #   documentclass: scrreprt



