project:
  type: book
  output-dir: _book

book:
  title: "Soil Dynamics and Earthquake Engineering"
  author: "Vikas Sharma"
  date: "2/06/2025"
  reader-mode: true
  search: true
  repo-url: https://github.com/poromechanics/sdee/
  site-url: https://poromechanics.github.io/sdee
  repo-actions: [edit, issue]
  downloads: [pdf,epub]
  sharing: [twitter, linkedin]
  favicon: ./figures/favicon.png
  cover-image: ./figures/cover.svg
  cover-image-alt: SDEE
  twitter-card: true
  page-navigation: true
  page-footer: 
    left: "Copyright 2025, Vikas Sharma" 
    right: 
      - icon: github
        href: https://github.com/vickysharma0812
      - icon: twitter
        href: https://twitter.com/vickysharma0812
      - icon: linkedin
        href: https://linkedin.com/in/vickysharma0812
  sidebar:
      style: docked
      background: light
  chapters:
    - index.md
    - intro.md
    - part: "Single Degree of Freedom System"
      chapters:
        - ./sdof/first-order-ode-tdg.md
        - ./sdof/second-order-ode-tdg.md
    - part: "Elastodynamics"
      chapters:
        - ./elastodynamics/elastodynamics-introduction.md
        - ./elastodynamics/elastodynamics-vstfem.md
        - ./elastodynamics/elastodynamics-numerical-examples.md
    - summary.md
    - references.md
  # appendices:
  # crossref:

bibliography: references.bib

comments:
  hypothesis: true

execute:
  freeze: auto

format:
  html:
    number-depth: 2
    theme:
      - cosmo
      - brand
  # pdf:
  #   documentclass: scrreprt



